version: '3.7'


services:
  #Api
  promocode-factory-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "promocode-factory-api"
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80;http://+:5000
      - "DefaultConnection=Host=promocode-factory-db;Database=PromoCodeFactoryDb;Username=postgres;Password=password;Port=5432"
    depends_on:
      - promocode-factory-db

  #Db
  promocode-factory-db:
    image: "postgres:13.2"
    container_name: "promocode-factory-db"
    working_dir: /application
    volumes:
      - ./db_data:/application
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=PromoCodeFactoryDb
