image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test

before_script:
  - 'dotnet restore src/Otus.Teaching.PromoCodeFactory.sln'

build:
  stage: build
  # ### Build all projects discovered from solution file.
  script:
    - 'dotnet build src/Otus.Teaching.PromoCodeFactory.sln --no-restore'

test:
  stage: test
  # ### Run the tests
  script:
    - 'dotnet test src/Otus.Teaching.PromoCodeFactory.sln --no-restore'

